---
- name: Set up Folder Structure
  tags: hostsetup

- name: Create Ansible Temp Folder
  ansible.windows.win_file:
    state: directory
    path: 'C:\Temp\ansible'

- name: Create ServiceNow Directory
  ansible.windows.win_file:
    state: directory
    path: 'C:\ServiceNow'

- name: Copy Tools Directory
  ansible.windows.win_copy:
    src: './files/tools'
    dest: 'C:\ServiceNow'
