---
- name: Restart MID Service
  ansible.windows.win_service:
    name: 'snc_mid_{{ item.name }}-{{ item.path }}'
    state: restarted
  when: item.state == 'restart'

- name: Stop MID Service
  ansible.windows.win_service:
    name: 'snc_mid_{{ item.name }}-{{ item.path }}'
    state: stopped
  when: item.state == 'down'

- name: Start MID Service
  ansible.windows.win_service:
    name: 'snc_mid_{{ item.name }}-{{ item.path }}'
    state: started
  when: item.state == 'up'
